### CREATE A PRODUCT
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "iPhone",
  "price": 850.00
}

### GET A PRODUCT
GET http://localhost:8000/products/41b1d616-7fea-45c9-a107-cfb8f8c0c031
Content-Type: application/json


### UPDATE A PRODUCT
PUT http://localhost:8000/products/41b1d616-7fea-45c9-a107-cfb8f8c0c031
Content-Type: application/json

{
  "name": "iPhone",
  "price": 850.0
}

### DELETE A PRODUCT
DELETE http://localhost:8000/products/95721e47-7a44-4b98-93f6-6d12108dd372
Content-Type: application/json

### GET ALL PRODUCTS
GET http://localhost:8000/products?page=1&limit=10&sort=desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODU0NTQ1NjIsInN1YiI6IjBkMjc2MzI3LThiOTQtNDQwMy05MzY2LTA4ZTg0OWY4M2RlYiJ9.GqLyIDZzDlEUq5Fa-bGSIIhVXUcpyvVfcymdZN85dKQ