version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: go-mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gomysql
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: go-redis
    platform: linux/amd64
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
