// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/proto/location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistanceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"` //optional
}

func (x *GetDistanceInput) Reset() {
	*x = GetDistanceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistanceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceInput) ProtoMessage() {}

func (x *GetDistanceInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceInput.ProtoReflect.Descriptor instead.
func (*GetDistanceInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *GetDistanceInput) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetDistanceInput) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type GetDistanceOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance int64 `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *GetDistanceOutput) Reset() {
	*x = GetDistanceOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_location_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistanceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceOutput) ProtoMessage() {}

func (x *GetDistanceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_location_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceOutput.ProtoReflect.Descriptor instead.
func (*GetDistanceOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistanceOutput) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_pkg_proto_location_proto protoreflect.FileDescriptor

var file_pkg_proto_location_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4c,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x32, 0x4f, 0x0a,
	0x0f, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x08,
	0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_location_proto_rawDescOnce sync.Once
	file_pkg_proto_location_proto_rawDescData = file_pkg_proto_location_proto_rawDesc
)

func file_pkg_proto_location_proto_rawDescGZIP() []byte {
	file_pkg_proto_location_proto_rawDescOnce.Do(func() {
		file_pkg_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_location_proto_rawDescData)
	})
	return file_pkg_proto_location_proto_rawDescData
}

var file_pkg_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_location_proto_goTypes = []interface{}{
	(*GetDistanceInput)(nil),  // 0: pb.GetDistanceInput
	(*GetDistanceOutput)(nil), // 1: pb.GetDistanceOutput
}
var file_pkg_proto_location_proto_depIdxs = []int32{
	0, // 0: pb.DistanceService.GetDistance:input_type -> pb.GetDistanceInput
	1, // 1: pb.DistanceService.GetDistance:output_type -> pb.GetDistanceOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_location_proto_init() }
func file_pkg_proto_location_proto_init() {
	if File_pkg_proto_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistanceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_location_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistanceOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_location_proto_goTypes,
		DependencyIndexes: file_pkg_proto_location_proto_depIdxs,
		MessageInfos:      file_pkg_proto_location_proto_msgTypes,
	}.Build()
	File_pkg_proto_location_proto = out.File
	file_pkg_proto_location_proto_rawDesc = nil
	file_pkg_proto_location_proto_goTypes = nil
	file_pkg_proto_location_proto_depIdxs = nil
}
