// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/proto/location.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DistanceServiceClient is the client API for DistanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistanceServiceClient interface {
	GetDistance(ctx context.Context, in *GetDistanceInput, opts ...grpc.CallOption) (*GetDistanceOutput, error)
}

type distanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistanceServiceClient(cc grpc.ClientConnInterface) DistanceServiceClient {
	return &distanceServiceClient{cc}
}

func (c *distanceServiceClient) GetDistance(ctx context.Context, in *GetDistanceInput, opts ...grpc.CallOption) (*GetDistanceOutput, error) {
	out := new(GetDistanceOutput)
	err := c.cc.Invoke(ctx, "/pb.DistanceService/GetDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistanceServiceServer is the server API for DistanceService service.
// All implementations must embed UnimplementedDistanceServiceServer
// for forward compatibility
type DistanceServiceServer interface {
	GetDistance(context.Context, *GetDistanceInput) (*GetDistanceOutput, error)
	mustEmbedUnimplementedDistanceServiceServer()
}

// UnimplementedDistanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDistanceServiceServer struct {
}

func (UnimplementedDistanceServiceServer) GetDistance(context.Context, *GetDistanceInput) (*GetDistanceOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistance not implemented")
}
func (UnimplementedDistanceServiceServer) mustEmbedUnimplementedDistanceServiceServer() {}

// UnsafeDistanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistanceServiceServer will
// result in compilation errors.
type UnsafeDistanceServiceServer interface {
	mustEmbedUnimplementedDistanceServiceServer()
}

func RegisterDistanceServiceServer(s grpc.ServiceRegistrar, srv DistanceServiceServer) {
	s.RegisterService(&DistanceService_ServiceDesc, srv)
}

func _DistanceService_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceServiceServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DistanceService/GetDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceServiceServer).GetDistance(ctx, req.(*GetDistanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DistanceService_ServiceDesc is the grpc.ServiceDesc for DistanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DistanceService",
	HandlerType: (*DistanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDistance",
			Handler:    _DistanceService_GetDistance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/location.proto",
}
